volumes:
  db:

services:
  app:
    container_name: stuff-blog-docker
    build: .
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
      - MONGODB_URI=ss
      - MONGODB_DATABASE=admin
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - db:/data/db
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
