version: "3.8"
services:
  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2222:2000
volumes:
  dbdata6:
