version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://127.0.0.1:27017/stuff

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: