version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:5.0.4
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 2000:2000
    environment:
      PORT: 2000
      MONGODB_URI: mongodb://mongo_db:27017/stuff
      DB_NAME: stuff
      NAME: stuff
    depends_on:
      - mongo_db

volumes:
  mongo_db: